###
GET http://localhost/learn-php/options-api/index.php

###
GET http://localhost/learn-php/options-api/index.php?offset=25

###
GET http://localhost/learn-php/options-api/index.php?name=foo2

###
POST http://localhost/learn-php/options-api/index.php
Content-Type: application/json

{"name": "foo2", "value": "new data", "comment":  "Just a test"}

###
PUT http://localhost/learn-php/options-api/index.php
Content-Type: application/json

{"name": "foo2", "value":  "updated"}

###
DELETE http://localhost/learn-php/options-api/index.php
Content-Type: application/json

{"name": "foo2"}