CREATE TABLE content (
  id SERIAL,
  title VARCHAR(1000) NOT NULL,
  type VARCHAR(100) NOT NULL DEFAULT 'html',
  content TEXT NOT NULL,
  slug VARCHAR(1000),
  created_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);